version: '3'

services:
  mongo-express:
    env_file:
      - .env
    image: mongo-express
    ports:
      - 8081:8081
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    env_file:
      - .env
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/mongodb-db:/data/db
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge